### ISSUE TITLE
npm false negative.

### ISSUE THREAD

**Issue by bp0lr** [visma-prodsec/confused#15]
Hi guys! 
thanks for this great tool!.

If someone has created an npm package but later was Unpublished, the tool returns a status code 200 but the takeover for this package is still possible.

I have found this testing the package ````console-shim````

![imagen](https://user-images.githubusercontent.com/5620128/107992015-96394a00-6fb6-11eb-90bc-dbd17be090b1.png)

![imagen](https://user-images.githubusercontent.com/5620128/107992111-c1239e00-6fb6-11eb-9946-6a989ab3ecc8.png)

![imagen](https://user-images.githubusercontent.com/5620128/107992146-d4366e00-6fb6-11eb-8539-74df593f7f84.png)

![imagen](https://user-images.githubusercontent.com/5620128/107992194-f16b3c80-6fb6-11eb-8160-1bfc552166c4.png)

thanks!

**Comment by joohoi** [comment]
Nice finding! I'll look into how to mitigate this. Should be pretty much doable, but I need to look how the response for a unpublished package looks like.

**Comment by lean0x2F** [comment]
@joohoi The response body will be a JSON object with the time->unpublished field (200 OK) response.
