### ISSUE TITLE
[NPM] Dependencies set as URLs are not takeovereable

### ISSUE THREAD

**Issue by lean0x2F** [visma-prodsec/confused#16]
Hi again!

AFAIK dependencies specified as a URL are not takeovereable, as it'll override the normal lookup mechanism and it will instruct NPM to download the dependency from a specific location:

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies

Some examples

```
"dep_name": "github_org_name/repo_name#2.2.0"
"dep_name": "https://github.com/github_org_name/repo_name#2.2.0"
"dep_name": "file:/test/path"
```

confused still flag these as vulnerable

Maybe the best way to fix this is by checking if the version part is valid semver, but there might be some edge cases ("`tag`"?)

**Comment by joohoi** [comment]
Thanks for opening the issue. The referencing PR fixes this issue
