### ISSUE TITLE
pip filter with tilde = gives incorrect false-positive package name.

### ISSUE THREAD

**Issue by bjhulst** [visma-prodsec/confused#20]
A requirements.txt entry with **tilde =** is not parsed correctly.

boto3~=2.3.4

it is parsed as package name   **boto3~**       but it should be _boto3_.

Tilde = is a valid syntax.
https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by joohoi** [comment]
This was fixed in #21
