### ISSUE TITLE
support continuations in pip requirements files

### ISSUE THREAD

**Issue by willkg** [visma-prodsec/confused#3]
pip requirements files can look like this:

```
appdirs==1.4.4 \
    --hash=sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41 \
    --hash=sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128 \
    # via black
```

That has the package pinned to a specific version plus hashes of the package download files. When pip is used to install packages specified like this, it downloads the file and verifies it against the hash in the requirements file. The continuations (`\`) are used to keep the file readable.

Given a requirements file like that, confused produces output like this:

```
Issues found, the following packages are not available in public package repositories:
 [!] --hash
 [!] --hash
```

Seems like confused doesn't support continuations (the `\`):

https://github.com/visma-prodsec/confused/blob/d0cafe92dca8bcacf76b3d8f36f37da679a9ca77/pip.go#L24-L35

**Comment by joohoi** [comment]
Thanks for opening the issue. It's definitely a bug, and I'll look into it!

**Comment by willkg** [comment]
Thank you!
